name: Deploy to EC2
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Make Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Assemble project to JAR
      - name: Build JAR with Gradle
        run: ./gradlew build -x test

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t project_backend:latest .
      
      # Tag Docker image
      - name: Tag Docker image
        run: docker tag project_backend:latest ${{ secrets.DOCKER_USERNAME }}/project_backend:latest
      
      # Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/project_backend:latest
      
      # SSH into EC2 instance and deploy
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/project_backend:latest
            docker stop project_backend || true
            docker rm project_backend || true
            docker run -d --name project_backend -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/project_backend:latest
